# Advanced DeepSeek Voice Agent Configuration

# Audio Processing Settings
audio:
  sample_rate: 16000
  chunk_size: 1024
  noise_reduction:
    enabled: true
    strength: 0.5
  enhancement:
    enabled: true
    normalize: true

# Emotion Detection Settings
emotion:
  enabled: true
  sensitivity: 0.7
  response_adaptation: true
  visual_indicators: true
  supported_emotions:
    - neutral
    - excited
    - calm
    - serious
    - happy
    - sad

# Voice Commands Settings
voice_commands:
  enabled: true
  sensitivity: 0.8
  language_support: true
  commands:
    clear_history: ["clear history", "reset conversation", "start over"]
    toggle_microphone: ["toggle microphone", "mic on", "mic off"]
    toggle_speech: ["toggle speech", "voice on", "voice off"]
    help: ["help", "show commands", "what can you do"]

# Multi-language Support
languages:
  default: "en"
  supported:
    en: "English"
    es: "Spanish"
    fr: "French"
    de: "German"
    it: "Italian"
    pt: "Portuguese"
    ru: "Russian"
    ja: "Japanese"
    ko: "Korean"
    zh: "Chinese"

# UI/UX Settings
ui:
  theme: "dark"
  emotion_colors:
    excited: "#ff6b6b"
    calm: "#4ecdc4"
    serious: "#45b7d1"
    neutral: "#96ceb4"
    happy: "#feca57"
    sad: "#a55eea"
  
  layout:
    sidebar_width: 300
    main_width: 800
    show_audio_viz: false
    compact_mode: false

# Performance Settings
performance:
  max_conversation_history: 50
  audio_buffer_size: 8192
  processing_timeout: 30
  api_timeout: 60

# Security Settings
security:
  api_key_validation: true
  session_timeout: 3600
  audio_cleanup: true
  conversation_encryption: false

# Advanced Features
features:
  real_time_transcription: false
  voice_activity_detection: true
  speaker_identification: false
  conversation_analytics: false
  custom_voice_training: false

# Logging Settings
logging:
  level: "INFO"
  file_logging: false
  console_logging: true
  audio_logging: false

